"""add mahasiswa db

Revision ID: 26c3a9a0786c
Revises: 957128b30bea
Create Date: 2024-01-30 01:44:55.926947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c3a9a0786c'
down_revision = '957128b30bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosen_dua', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'dosen', ['dosen_dua'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dosen_dua')

    # ### end Alembic commands ###
