"""add user db

Revision ID: 65284e550e78
Revises: 0d74448a6f04
Create Date: 2024-01-30 01:18:35.641909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65284e550e78'
down_revision = '0d74448a6f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
